### ISSUE TITLE
Adicionar o mongoose

### ISSUE THREAD

**Issue by RodolfoSilva** [andrehrf/hawk#1]
Poderíamos adicionar o mongoose a este projeto, para auxiliar na ampliação dos modelos futuros... 
O que acha?
Assim poderíamos ter esquemas padronizados.

**Comment by andrehrf** [comment]
Como defino esquemas padronizados se não sei que tipo de informação cada usuário do hawk deseja coletar em seus mapeamentos/atualizações? o fato do mongo não trabalhar com schema é muito bom para o projeto, não vejo muito sentido no seu pedido
